# fly.toml app configuration file generated for arc42-stats on 2023-10-20T17:36:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "arc42-stats"
primary_region = "mad"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
